import m from "mithril";
import {button} from "../index";
import {code} from "./example-utils";

export default {
    view: () => [
        m(button, "Flat"),
        m(code, `m(button, "Flat")`),
        m(button, {disabled: true}, "Disabled"),
        m(code, `m(button, {disabled: true}, "Disabled")`),
        m(button, {class: "mdc-button--raised"}, "Raised"),
        m(code, `m(button, {class: "mdc-button--raised"}, "Raised")`),
        m(button, {disabled: true, class: "mdc-button--raised"}, "Disabled and Raised"),
        m(code, `m(button, {disabled: true, class: "mdc-button--raised"}, "Disabled and Raised")`),
        m(button, {class: "mdc-button--dense"}, "Dense"),
        m(code, `m(button, {class: "mdc-button--dense"}, "Dense")`),
        m(button, {class: "mdc-button--dense", disabled: true}, "Dense and Disabled"),
        m(code, `m(button, {class: "mdc-button--dense", disabled: true}, "Dense and Disabled")`),
        m(button, {class: "mdc-button--dense mdc-button--raised"}, "Dense and Raised"),
        m(code, `m(button, {class: "mdc-button--dense mdc-button--raised"}, "Dense and Raised")`),
        m(button, {class: "mdc-button--dense mdc-button--raised", disabled: true}, "Dense, Disabled and Raised"),
        m(code, `m(button, {class: "mdc-button--dense mdc-button--raised", disabled: true}, "Dense, Disabled and Raised")`),
        m(button, {class: "mdc-button--compact"}, "Compact"),
        m(code, `m(button, {class: "mdc-button--compact"}, "Compact")`),
        m(button, {class: "mdc-button--compact", disabled: true}, "Compact and Disabled"),
        m(code, `m(button, {class: "mdc-button--compact", disabled: true}, "Compact and Disabled")`),
        m(button, {class: "mdc-button--compact mdc-button--raised"}, "Compact and Raised"),
        m(code, `m(button, {class: "mdc-button--compact mdc-button--raised"}, "Compact and Raised")`),
        m(button, {class: "mdc-button--compact mdc-button--raised", disabled: true}, "Compact, Disabled and Raised"),
        m(code, `m(button, {class: "mdc-button--compact mdc-button--raised", disabled: true}, "Compact, Disabled and Raised")`),
        m(button, {class: "mdc-button--primary"}, "Primary colored"),
        m(code, `m(button, {class: "mdc-button--primary"}, "Primary colored")`),
        m(button, {class: "mdc-button--primary", disabled: true}, "Primary colored and Disabled"),
        m(code, `m(button, {class: "mdc-button--primary", disabled: true}, "Primary colored and Disabled")`),
        m(button, {class: "mdc-button--primary mdc-button--raised"}, "Primary colored and Raised"),
        m(code, `m(button, {class: "mdc-button--primary mdc-button--raised"}, "Primary colored and Raised")`),
        m(button, {class: "mdc-button--primary mdc-button--raised", disabled: true}, "Primary colored, Disabled and Raised"),
        m(code, `m(button, {class: "mdc-button--primary mdc-button--raised", disabled: true}, "Primary colored, Disabled and Raised")`),
        m(button, {class: "mdc-button--accent"}, "Accent colored"),
        m(code, `m(button, {class: "mdc-button--accent"}, "Accent colored")`),
        m(button, {class: "mdc-button--accent", disabled: true}, "Accent colored and Disabled"),
        m(code, `m(button, {class: "mdc-button--accent", disabled: true}, "Accent colored and Disabled")`),
        m(button, {class: "mdc-button--accent mdc-button--raised"}, "Accent colored and Raised"),
        m(code, `m(button, {class: "mdc-button--accent mdc-button--raised"}, "Accent colored and Raised")`),
        m(button, {class: "mdc-button--accent mdc-button--raised", disabled: true}, "Accent colored, Disabled and Raised"),
        m(code, `m(button, {class: "mdc-button--accent mdc-button--raised", disabled: true}, "Accent colored, Disabled and Raised")`),
        m(button, {tagName: "div"}, "Div"),
        m(code, `m(button, {tagName: "div"}, "Div")`),
        m(button, {tagName: "a", href: "#"}, "Link"),
        m(code, `m(button, {tagName: "a", href: "#"}, "Link")`)
    ]
};